# Configuración de Base de Datos
db.url=jdbc:mysql://localhost:3306/quick_delivery_db?serverTimezone=UTC&useSSL=false
db.user=root
db.driver=com.mysql.cj.jdbc.Driver

#PLACEHOLDER#
db.password= ${DB_PASSWORD}